apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "slumlord.fullname" . }}-manager
  labels:
    {{- include "slumlord.labels" . | nindent 4 }}
rules:
  # SlumlordSleepSchedule resources
  - apiGroups:
      - slumlord.io
    resources:
      - slumlordsleepschedules
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - slumlord.io
    resources:
      - slumlordsleepschedules/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - slumlord.io
    resources:
      - slumlordsleepschedules/finalizers
    verbs:
      - update
  # Deployments
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  # StatefulSets
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  # CronJobs
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  # CNPG Clusters
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusters
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  # FluxCD HelmReleases
  - apiGroups:
      - helm.toolkit.fluxcd.io
    resources:
      - helmreleases
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  # FluxCD Kustomizations
  - apiGroups:
      - kustomize.toolkit.fluxcd.io
    resources:
      - kustomizations
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  {{- if .Values.idleDetector.enabled }}
  # SlumlordIdleDetector resources
  - apiGroups:
      - slumlord.io
    resources:
      - slumlordidledetectors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - slumlord.io
    resources:
      - slumlordidledetectors/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - slumlord.io
    resources:
      - slumlordidledetectors/finalizers
    verbs:
      - update
  # Metrics API (for idle detection)
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
  {{- end }}
