apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "slumlord.fullname" . }}-manager
  labels:
    {{- include "slumlord.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "slumlord.fullname" . }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "slumlord.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
