{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slumlord.fullname" . }}-metrics
  labels:
    {{- include "slumlord.labels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "slumlord.selectorLabels" . | nindent 4 }}
{{- end }}
