apiVersion: v2
name: slumlord
description: A Helm chart for Slumlord - Kubernetes operator for cost optimization
type: application
version: 2.13.0
appVersion: "2.13.0"
keywords:
  - kubernetes
  - operator
  - cost-optimization
  - sleep-schedule
home: https://github.com/cschockaert/slumlord
sources:
  - https://github.com/cschockaert/slumlord
maintainers:
  - name: cschockaert
annotations:
  artifacthub.io/operator: "true"
  artifacthub.io/license: Apache-2.0
